name: CI/CD

on: [push]

jobs:
  Run Lint and Unit Tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install
      - run: npm format
      - run: npm lint
      - run: npm test
